version: '3.8'

services:
  webhook:
    build: .
    container_name: github-webhook-updater
    ports:
      - "5005:5005"
    volumes:
      - /Users/justin/Developer/github-webhook-updater/test:/host-data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env