version: '3.8'

services:
  webhook:
    build: .
    container_name: github-webhook-updater
    ports:
      - "5005:5005"
    volumes:
      - /Users/justin/.ssh/id_ed25519:/root/.ssh/id_ed25519
    env_file:
      - .env